unstable_features = true
indent_style = "Block"
max_width = 100
comment_width = 100
wrap_comments = true
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
condense_wildcard_suffixes = false
format_strings = true
normalize_comments = true
reorder_imports = true
use_field_init_shorthand = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
