unstable_features = true
indent_style = "Visual"
verbose = false
max_width = 100
comment_width = 100
wrap_comments = true
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
write_mode = "Overwrite"
condense_wildcard_suffixes = false
format_strings = true
# normalize_comments = true
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
use_field_init_shorthand = true
error_on_line_overflow = false