[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]
workspace = "../"
build = "build.rs"
edition = "2018"

# IMPORTANT: If you add/remove/update dependencies here, please also
# update Cargo.toml in https://gitlab.com/BuildStream/cargo-fetcher
# (just submit a merge request there).
#
# BuildStream/cargo-fetcher lets GNOME's BuildStream continuous build
# service know which dependencies are required.
#
# Please update your dependencies here, then run "cargo update" to
# regenerate librsvg/Cargo.lock, and copy the resolved version numbers
# from there into cargo-fetcher/Cargo.toml.

[dependencies]
cairo-rs = { version="0.7.0", features=["v1_16"] }
cairo-sys-rs = "0.9.0"
cssparser = "0.25.5"
data-url = "0.1"
downcast-rs = "^1.0.0"
encoding = "0.2.33"
float-cmp = "0.5.2"
gdk-pixbuf = "0.7.0"
gdk-pixbuf-sys = "0.9.0"
gio = { version="0.7.0", features=["v2_48"] } # per configure.ac
gio-sys = "0.9.0"
glib = { version="0.8.0" }
glib-sys = "0.9.0"
itertools = "0.8"
language-tags = "0.2.2"
lazy_static = "1.0.0"
libc = "0.2"
locale_config = "*" # recommended explicitly by locale_config's README.md
markup5ever = "0.9"
nalgebra = "0.18"
num-traits = "0.2"
pango = "0.7.0"
pango-sys = "0.9.0"
pangocairo = "0.8.0"
phf = "0.7.21"
rayon = "1"
rctree = "0.3.3"
regex = "1"
url = "2"
xml-rs = "0.8.0"
string_cache = "=0.7.3"

[dev-dependencies]
criterion = "0.2"

[lib]
name = "rsvg_internals"

[[bench]]
name = "box_blur"
harness = false

[[bench]]
name = "composite"
harness = false

[[bench]]
name = "lighting"
harness = false

[[bench]]
name = "pixel_iterators"
harness = false

[[bench]]
name = "srgb"
harness = false
