# Configuration for https://gitlab.gnome.org/GNOME/gi-docgen

[library]
version = "2.61.2"
description = "Librsvg - load and render SVG documents"
authors = "Librsvg developers"
license = "LGPL-2.1-or-later"
browse_url = "https://gitlab.gnome.org/GNOME/librsvg/"
repository_url = "https://gitlab.gnome.org/GNOME/librsvg.git"
website_url = "https://wiki.gnome.org/Projects/LibRsvg"
devhelp = true
search_index = true
logo_url = "librsvg-r.svg"

[source-location]
# The base URL for the web UI
base_url = "https://gitlab.gnome.org/GNOME/librsvg/-/blob/main/"
# The format for links, using "filename" and "line" for the format
file_format = "{filename}#L{line}"

[theme]
name = "basic"
show_index_summary = true
show_class_hierarchy = true

[extra]
content_files = [
  "overview.md",
  "recommendations.md",
  "migrating.md"
]
content_images = [
  "librsvg-r.svg"
]
urlmap_file = "urlmap.js"

[[object]]
name = "Rsvg.DEPRECATED_FOR"
hidden = true
