[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]

[dependencies]
libc = "0.2"
bitflags = ""

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo.git"
#git = "https://github.com/federicomenaquintero/cairo.git"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo.git"
#git = "https://github.com/federicomenaquintero/cairo.git"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.1"

[lib]
name = "rsvg_internals"
crate-type = ["staticlib"]
